### ISSUE TITLE
Meta issue: Add these algorithms

### ISSUE THREAD

**Issue by r1walz** [r1walz/cookbook#6]
This is a list to track the progress of various algorithms to be added:

- Fundamentals
    - [x] Binary Exponentiation 
    - [ ] Extended GCD
    - [ ] Linear Diophantine Solver
    - [ ] Fibonacci
- Prime Numbers
    - [x] Sieve
    - [ ] Primality test
    - [ ] Factorization
- Array
    - [ ] Some question to make use of radix
- Trees
    - [x] Disjoint Set Union
    - [ ] Sqrt Decomposition
    - [ ] Fenwick Tree
- Graphs
    - [x] Depth First Search
    - [ ] Breadth First Search
    - [x] Finding Connected Components
    - [ ] Shortest Path using Dijkstra
    - [ ] Bellman-Ford Algorithm
    - [x] Floyd-Warshall Algorithm
    - [ ] Minimum Spanning Tree algorithms
    - [ ] Bi-partite graph check
    - [ ] Cycle Detection Algorithms
- String
    - [ ] String Hashing algorithms
    - [ ] Rabin-Karp
    - [ ] Knuth-Morris-Pratt
    - [x] Z-function
    - [ ] Aho-Corasick algorithm
    - [ ] Suffix Tree
    - [ ] Expression parsing
    - [ ] Manacher algorithm
- Dynamic Programming
    - [ ] 0-1 Knapsack problem
    - [ ] Rod-cutting problem
    - [ ] Word break problem
    - [ ] Egg dropping puzzle
    - [ ] Longest common subsequence
    - [x] Longest increasing subsequence
- Miscellaneous
    - [ ] Enumerating submasks of a bitmask
    - [ ] Arbitrary presision arithmetic
    - [ ] Fast Fourier transform
    - [ ] Operations on polynomials and series
